### ISSUE TITLE
Failed getting contents of http: Filesystem has no item svn: path not found

### ISSUE THREAD

**Issue by tapasalok** [rombert/ereviewboard#142]
We have created one review request but post that when I perform a Diff from eReviewBoard, I am getting the below error

 Failed getting contents of http://******_/svn/Path Trial @73571:
 org.apache.subversion.javahl.ClientException: Filesystem has no item svn:
 '/svn/!svn/bc/73602/http:/**_****/svn/Path%20Trial/slider.js' path not found

![image](https://cloud.githubusercontent.com/assets/1433281/6911523/63e42a14-d77f-11e4-8885-2f4a912ea211.png)

Kindly find below information:
1. Review Request was created using Eclipse or Review Board Web browser ?
   [Tapas]: Using Web browser
2. We have to make sure your local checkout is up to date.
   [Tapas]: It is up to date
3. Did the user directly created diff files / patch files from eclipse and upload them to review board UI tool or using svn command ?
   [Tapas]: using eclipse

Please let us know how to proceed.

**Comment by selsemore** [comment]
I don't know if this is the problem here, but I submitted a pull request that fixes a problem like this in the case where the file existed in the revision at which the patch was created but does not exist in the HEAD revision.
https://github.com/rombert/ereviewboard/pull/147

**Comment by rombert** [comment]
@tapasalok - I have built a new pre-release based on @selsemore's fix. Can you please download it from https://github.com/rombert/ereviewboard/releases/tag/ereviewboard-0.13.4-pre-2 and let us know if this fixes the problem?

**Comment by rombert** [comment]
No feedback, considering fixed.
