### ISSUE TITLE
Support latest Subclipse release

### ISSUE THREAD

**Issue by markphip** [rombert/ereviewboard#153]
I have recently moved Subclipse to Github and restructured the project and build process to use Maven etc.

In the process, I am also updating the minimum Eclipse requirement so I just bumped up to a new version number (4.2.0).

The eReviewboard feature.xml has an incorrect requires dependency that prevents it from installing.  I have posted a pull request to fix this.  It would be great if you could post a new version of the plugin so people can install it.

**Comment by rombert** [comment]
Thanks for the heads-up. I will perform a release at the end of this week, I need to clear up some issues with my code signing certificate. Or if you have a code signing certificate that you can use you can go ahead and use it and I will guide you through the release process.

**Comment by rombert** [comment]
Sorry for the large delay - I did not manage to get a code signing certificate so I just released with unsigned content. Definitely better than no release
